[package]
name = "scars"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
sca = { path = "../sca" }
